// src/components/send-box.vue
<template>
  <div id="send-box" :class="messageBoxClass" :style="messageBoxStyle">

    <div id="voice-bar">
      <div id="click-to-change" title="Change character" @click="$emit('open-character-menu')">
        {{ currentVoiceName }}
      </div>
      <button class="icon-button" @click="$emit('open-character-menu')">
        <i class="material-icons" title="Change character">people</i>
      </button>
      <button class="icon-button" @click="$refs.imageDialog.open(null)">
        <i class="material-icons" title="Post image">image</i>
      </button>
      <button class="icon-button" @click="showFormatGuide">
        <i class="material-icons" title="Formatting info">text_fields</i>
      </button>
    </div>

    <div id="typing-area">
      <textarea
        rows="3"
        placeholder="Type your message."
        maxlength="10000"
        :disabled="isMsgBoxSending"
        v-model="msgBoxText"
        @keydown.enter.ctrl.exact="($event.preventDefault(), submit())"
        @keydown.enter.exact="pressEnterToSend ? ($event.preventDefault(), submit()) : null"
        @input="resizeTextareaOnInput($event, 3, 6)"
      ></textarea>
      <template v-if="!isMsgBoxSending">
        <button class="icon-button" :disabled="!msgBoxValid" @click="submit">
          <i class="material-icons" title="Send">send</i>
        </button>
      </template>
      <template v-if="isMsgBoxSending">
        <div id="send-loader-container">
          <i class="material-icons">hourglass_full</i>
        </div>
      </template>
    </div>

    <image-dialog ref="imageDialog" :send="send"></image-dialog>

  </div>
</template>

<script>
  const tinycolor = window.tinycolor;
  import ImageDialog from './image-dialog.vue';

  export default  {
    components: {
      ImageDialog
    },
    props: [
      'charasById',
      'pressEnterToSend',
      'send',
      'voice',
    ],
    data() {
      return {
        msgBoxText: '',
        isMsgBoxSending: false,
      };
    },
    computed: {
      currentChara() {
        if (this.voice.type !== 'chara') return undefined;
        return this.charasById[this.voice.charaId]
      },
      currentVoiceName() {
        if (this.voice.type === 'narrator') return 'Narrator';
        if (this.voice.type === 'ooc') return 'Out of Character';
        return this.currentChara.name;
      },
      currentCharaColor() {
        if (this.voice.type !== 'chara') return undefined;
        return this.currentChara.color;
      },
      messageBoxClass() {
        return 'send-box-' + this.voice.type;
      },
      messageBoxStyle() {
        if (this.voice.type !== 'chara') return {};
        else return {
          'background-color': this.currentCharaColor,
          'color': tinycolor(this.currentCharaColor).isLight() ? 'black' : 'white',
        };
      },
      msgBoxValid() {
        return this.msgBoxText.trim().length > 0;
      },
    },
    methods: {
      applyShortcutsToMessage(msg) {
        if (msg.type !== 'ooc') {
          var oocShortcuts = [
            /^\({2,}\s*(.*?[^\s])\s*\)*$/g, // (( message text ))
            /^\{+\s*(.*?[^\s])\s*\}*$/g, // { message text }, {{ message text }}, ...
            /^\/\/\s*(.*[^\s])\s*$/g // //message text
          ];
          for (var i = 0; i < oocShortcuts.length; ++i) {
            var regex = oocShortcuts[i];
            var match = regex.exec(msg.content);
            if (match) {
              return { type: 'ooc', content: match[1] };
            }
          }
        }
        return msg;
      },
      submit() {
        if (!this.msgBoxValid) return;

        var wasFocused = (document.activeElement === document.querySelector('#typing-area textarea'));

        var data = {
          content: this.msgBoxText,
          type: this.voice.type,
          charaId: this.voice.charaId || undefined,
        };

        data = this.applyShortcutsToMessage(data);

        this.isMsgBoxSending = true;

        this.send(data)
          .then(() => {
            this.msgBoxText = '';
            this.isMsgBoxSending = false;
            if (wasFocused) this.$nextTick(() => document.querySelector('#typing-area textarea').focus());
          })
          .catch(() => {
            this.isMsgBoxSending = false;
          });
      },
      resizeTextareaOnInput($event, minRows, maxRows) {
        var el = $event.target;
        while (el.rows > minRows && el.scrollHeight <= el.offsetHeight) {
          el.rows = el.rows - 1;
        }
        while (el.rows < maxRows && el.scrollHeight > el.offsetHeight) {
          el.rows = el.rows + 1;
        }
      },
      showFormatGuide() {
        window.open('/format', '_blank').focus();
      },
    }
  };
</script>

// src/app/rp/components/send-box.component.ts
import { Component, Output, EventEmitter, ViewContainerRef, ChangeDetectionStrategy, Input } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { FormatGuideDialog } from './format-guide-dialog.component';
import { ImageDialogComponent } from './image-dialog.component';
import { RpVoice } from '../models/rp-voice';
import { RpChara } from '../models/rp-chara';

@Component({
  selector: 'send-box',
  template: `
    <div id="send-box" fxLayout="column" [class]="elementClass" [style.background-color]="chara?.color" [style.color]="chara?.color|bw">

        <div id="voice-bar" fxLayout="row" fxLayoutAlign="center center">

            <div id="click-to-change" fxFlex fxLayout="row" fxLayoutAlign="start center" fxLayoutGap="10px" matTooltip="Change character" matTooltipPosition="above" (click)="openCharaSelector()">
                <ng-container *ngIf="isNarrator">
                    Narrator
                </ng-container>

                <ng-container *ngIf="isOOC">
                    Out of character
                </ng-container>

                <ng-container *ngIf="isChara">
                    {{chara.name}}
                </ng-container>
            </div>

            <button mat-icon-button (click)="openCharaSelector()">
                <mat-icon aria-label="Change character" matTooltip="Change character" matTooltipPosition="above">people</mat-icon>
            </button>

            <button mat-icon-button (click)="showImageDialog()">
                <mat-icon aria-label="Post image" matTooltip="Post image" matTooltipPosition="above">image</mat-icon>
            </button>

            <button mat-icon-button (click)="showFormatGuideDialog()">
                <mat-icon aria-label="Open post format guide" matTooltip="Formatting info" matTooltipPosition="above">text_fields</mat-icon>
            </button>

        </div>

        <div id="typing-area" fxLayout="row" fxLayoutAlign="center center">

            <textarea fxFlex matTextareaAutosize matAutosizeMinRows="3" [(ngModel)]="content" (ngModelChange)="contentChange.emit($event)" placeholder="Type your message." maxlength="10000" (keypress)="keypressCheckEnter($event)"></textarea>

            <button mat-icon-button [disabled]="!valid()" (click)="sendMessage()">
                <mat-icon aria-label="Send" matTooltip="Send" matTooltipPosition="above">send</mat-icon>
            </button>

        </div>

    </div>
  `,
  styleUrls: ['./send-box.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SendBoxComponent {

  @Input() voice: RpVoice;
  @Input() content = '';
  @Input() pressEnterToSend: boolean;
  @Output() contentChange: EventEmitter<string> = new EventEmitter();
  @Output() onSendMessage: EventEmitter<[string, RpVoice]> = new EventEmitter();
  @Output() onSendImage: EventEmitter<string> = new EventEmitter();
  @Output() changeCharacter: EventEmitter<void> = new EventEmitter();

  constructor(
    private dialog: MatDialog,
    private viewContainerRef: ViewContainerRef,
  ) { }

  get isNarrator() {
    return this.voice === 'narrator';
  }

  get isOOC() {
    return this.voice === 'ooc';
  }

  get isChara() {
    return !(typeof this.voice === 'string');
  }

  get chara() {
    return this.isChara ? (this.voice as RpChara) : null;
  }

  get elementClass() {
    return this.isChara ? 'send-box-chara' : 'send-box-' + this.voice;
  }

  valid() {
    return this.content.trim().length > 0;
  }

  sendMessage() {
    if (!this.valid()) return;

    let voice = this.voice;
    let content = this.content;

    // shortcut to send ooc messages; if not on the actual OOC character,
    //  you can send a message inside of (()) et all, as a shortcut to change
    //  that specific message to an OOC message
    if (voice !== 'ooc') {
      [
        /^\({2,}\s*(.*?[^\s])\s*\)*$/g, // (( message text ))
        /^\{+\s*(.*?[^\s])\s*\}*$/g, // { message text }, {{ message text }}, ...
        /^\/\/\s*(.*[^\s])\s*$/g // //message text
      ].find(regex => {
        const match = regex.exec(content);
        if (match) {
          voice = 'ooc';
          content = match[1];
        }
        return !!match;
      });
    }

    if (!content.trim()) return;

    this.onSendMessage.emit([content, voice]);

    this.content = '';
  }

  openCharaSelector() {
    this.changeCharacter.emit();
  }

  showImageDialog() {
    const dialogRef = this.dialog.open(ImageDialogComponent, { viewContainerRef: this.viewContainerRef });
    dialogRef.beforeClose().subscribe(url => {
      this.onSendImage.emit(url);
    });
  }

  keypressCheckEnter($event: KeyboardEvent) {
    const keyCode = $event.keyCode || $event.which;
    if (keyCode !== 13) return;

    if ($event.shiftKey) return;

    if (this.pressEnterToSend || $event.ctrlKey) {
      this.sendMessage();
      return false;
    }
  }

  showFormatGuideDialog() {
    this.dialog.open(FormatGuideDialog);
  }
}
